version: '2'
services:
    evalueat-app:
        image: evalueat
        environment:
            - 'JAVA_OPTS=-Xmx512m -Xms256m -agentlib:jdwp=transport=dt_socket,address=8001,server=y,suspend=n'
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:mariadb://evalueat-mariadb:3306/evalueat'
            - JHIPSTER_SLEEP=10
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - '8001:8001'
            - '8081:8081'
    evalueat-mariadb:
        image: 'mariadb:10.3.7'
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=evalueat
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    
    evalueatgateway-app:
        image: evalueatgateway
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:mariadb://evalueatgateway-mariadb:3306/evalueatgateway'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - '8080:8080'
    evalueatgateway-mariadb:
        image: 'mariadb:10.3.7'
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=evalueatgateway
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
